### SingUp
POST http://localhost:3000/user
Content-Type: application/json 

{
    "name": "teste",
    "email": "teste@email.com",
    "password": "senha"
}

### LOgin
POST http://localhost:3000/user/login
Content-Type: application/json 

{
    "email": "teste@email.com",
    "password": "senha"
}

### Get All Users
GET http://localhost:3000/user

### Get User By Id
GET http://localhost:3000/user/26414a26-c230-44f6-9322-99aa48652fb2

### Delete User
DELETE http://localhost:3000/user/74e8d0e2-a73b-452e-9539-09f6f3345422
### 

GET http://localhost:3000/movies

### Get Movie By Id
GET http://localhost:3000/movies/1

### Resgister Movie
POST http://localhost:3000/movies
Content-Type: application/json

{
    "name": "teste",
    "category": "teste",
    "premiere_date": "2022/12/22",
    "description": "description",
    "duration": 120
}

### Edit Movie
PATCH   http://localhost:3000/movies/1
Content-Type: application/json

{
    "name": "teste",
    "category": "teste",
    "premiere_date": "2022/12/12",
    "description": "description",
    "duration": 120
}

### Delete Movies
DELETE  http://localhost:3000/movies/1
