### SingUp
POST http://localhost:3000/user
Content-Type: application/json 

{
    "name": "teste",
    "email": "teste@email.com",
    "password": "senha"
}

### Login
# @name login
POST http://localhost:3000/user/login
Content-Type: application/json 

{
    "email": "teste@email.com",
    "password": "senha"
}

###
@token = {{login.response.body.token}}

### Get All Users
GET http://localhost:3000/user
Authorization: {{token}}

### Get User By Id
GET http://localhost:3000/user/36fe45d9-6a2d-4036-9c7a-ce0f96ddf4a9
Authorization: {{token}}

### Delete User
DELETE http://localhost:3000/user/74e8d0e2-a73b-452e-9539-09f6f3345422
Authorization: {{token}}

### Get All Movies
GET http://localhost:3000/movies
Authorization: {{token}}

### Get Movie By Id
GET http://localhost:3000/movies/
Authorization: {{token}}

### Resgister Movie
POST http://localhost:3000/movies
Authorization: {{token}}
Content-Type: application/json

{
    "name": "teste",
    "category": "teste",
    "premiere_date": "2022/12/22",
    "description": "description",
    "duration": 120
}

### Edit Movie
PATCH   http://localhost:3000/movies/b79a2cf2-068b-42b9-8ba2-a8310bc92bb7
Authorization: {{token}}
Content-Type: application/json

{
    "name": "teste",
    "category": "teste",
    "premiere_date": "2022/12/12",
    "description": "description",
    "duration": 120
}

### Delete Movies
DELETE  http://localhost:3000/movies/b79a2cf2-068b-42b9-8ba2-a8310bc92bb7
Authorization: {{token}}
